dataset: smmnist

dataset_path: data

epochs: 50

learning_rate: 0.001

n_past: 10
n_future: 10
image_width: 64
n_eval: 20
num_digits: 2

batch_size: 32

# Scheduler
factor: 0.1

patience: 10

# Logging
log_freq: 100